linters:
  HexNotation:
    style: "lowercase"
  HexLength:
    style: "long"
  SingleLinePerSelector:
    enabled: false
  LeadingZero:
    style: "include_zero"
  NestingDepth:
    max_depth: 4
  SelectorDepth:
    max_depth: 4
  StringQuotes:
    style: "single"
  SelectorFormat:
    enabled: false
