meta:
  title: "Dan Schlosser"
  description: "Co-founder, Ambrook — we're hiring! Previously, product manager at The New York Times, Google, and Covid Act Now, tech lead at The Next 50, founder and web developer at Minimill, and CS at Columbia. Email me at dan@schlosser.io or tweet @danrschlosser."
  facebook_image: "/img/res/1600/cover-corner.png"
  twitter_image: "/img/res/1600/cover-corner.png"
  image: "/img/res/1600/cover-corner.png"
  twitter_handle: "@danrschlosser"
  google_analytics_id: "UA-40705748-1"
  domain: "schlosser.io"
  root: "https://schlosser.io"

name: "Dan Schlosser"
markdown: kramdown
permalink: "/:categories/:title/"
highlighter: rouge

# Build info
incremental: true
plugins:
  - jekyll-redirect-from
include:
  - font
exclude:
  - node_modules
  - Gulpfile.js
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - LICENSE.md
  - yarn.lock

collections:
  talks:
    title_singular: Talk
    output: true
    permalink: /:collection/:title/
  writing:
    title_singular: Writing
    output: true
    permalink: /:collection/:title/
  projects:
    title_singular: Project
    output: true
    permalink: /:collection/:title/
  lists:
    title_singular: List
    output: true
    permalink: /:collection/:title/
  travel:
    title_singular: Travel
    output: true
    permalink: /:collection/:title/
  teams:
    title_singular: Team
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
    values:
      layout: default
      hero_style: normal
  - scope:
      path: ""
      type: writing
    values:
      layout: blog_post
      related_posts: writing
  - scope:
      path: ""
      type: projects
    values:
      layout: project
      cta: Check it out
      link: ""
      related_posts: projects
  - scope:
      path: ""
      type: lists
    values:
      layout: blog_post
      related_posts: lists
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      hero_style: normal
      cta: Check it out
      related_posts: talks
  - scope:
      path: ""
      type: travel
    values:
      layout: trip
      hero_style: full_bleed
      related_posts: travel
  - scope:
      path: ""
      type: teams
    values:
      layout: team
      hero_style: normal
      related_posts: teams
